version: 0.0.{build}

image: Ubuntu1804

environment:
  nodejs_version: 10

install:
  - nvm install $nodejs_version
  - npm i -g npm
  - npm i -g @angular/cli@latest

build_script:
  - cd src/web-ui
  - npm ci
  - ng build --prod
  
test: off
