apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    {{- include "numchen.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "numchen.ui.selector" . | nindent 4 }}
